theme: jekyll-theme-minimal
title: Sunkyoo Hwang
description: Lecturer & Author for Image Processing, Computer Vision, OpenCV, Deep Learning, C/C++, Python, Java, Android, etc.
logo: /assets/img/sunkyoo.jpg
show_downloads: false
google_analytics: UA-132973055-1